// ECR repository that stores Docker images generated by CI/CD.
// scan_on_push helps detect vulnerabilities early.
resource "aws_ecr_repository" "app" {
  name                 = var.ecr_repository_name
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = true
  }

  force_delete = true
}

// Lifecycle policy to prevent unlimited growth in ECR.
// Keeps only the last N images (configurable via variable).
resource "aws_ecr_lifecycle_policy" "app" {
  repository = aws_ecr_repository.app.name

  policy = jsonencode({
    rules = [
      {
        rulePriority = 1
        description  = "Keep only recent images"
        selection = {
          tagStatus   = "any"
          countType   = "imageCountMoreThan"
          countNumber = var.ecr_image_retention_count
        }
        action = {
          type = "expire"
        }
      }
    ]
  })
}

// Centralized CloudWatch log group for ECS tasks and containers.
resource "aws_cloudwatch_log_group" "ecs" {
  name              = "/ecs/${var.ecs_cluster_name}/${var.project_name}"
  retention_in_days = 7
}

// ECS cluster where services and tasks will run.
// Container Insights enables additional CloudWatch metrics.
resource "aws_ecs_cluster" "main" {
  name = var.ecs_cluster_name

  setting {
    name  = "containerInsights"
    value = "enabled"
  }
}